travis:
  secure:
    BINSTAR_TOKEN: Viv0/InGNc3sp20Dcfo0YMQwXhYrh9mKa1rGVyfpefEe4bGTLe3fnNUtu6tAA9oxLAaPGJyQmvtLPUvxCNSfz4eemYZMH2kkwCyj2OsL5XEJnNdCDsOfTD5ne6geBlrB54hJW8ZqTteZ6zlvdS4P8gm0p/XHVXkf0xqXEzgnjBglNk8AGUMNhOVWyxBHOKVsIS4M3812J9MlpsNCTqf8UDnX9O/p92cNcIfXQYZbMRaz7nmsd/ztyBJ88HBqzJ0URxcZsahvZWGTFH1VtMXq+qa6kg/2IRaJGxrLTTHXsdgwoaeq6m3RfTtTtR7sfN3T+MXXqgebHzqjt/Kd6baCb1m6eXVAIa0DAMcww/gR8tVidANOCvK8ftBVYUb6i7CGTjbdNcRAEiQSl6vSbs341B8PJGZctZZJZFg/GZXehLS3AoL8oFIy18bD92jfwRVWDlEuuSjrWlwBA17aYi3NJUNDODndICzZHvtsXwrAWe5w0DBgJCcq+oD06w80Ec2T2dlpetbNamKXFgW2aDP8gJH4qy+4NZQYdrddPBrLwAXd42VGspipjd7nLHvU0Yv1iiOUAYGg7q9oNh6Xbv7XauXrcv64NbSCsVkoTSX1JjVtUBdp3K7ziw0nQ2ogSF1m9CYchh5vcgGeCFbxtu85+qPYDDVreNcrvpFzD18kN6c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
