travis:
  secure:
    BINSTAR_TOKEN: UCtY3t74ybvnL+YtXa/fDj/HZotEPo2yh9+pvlKaU3IstY/2He/Dvm//iLEoopQMeZKgFjielEI4BNbMUiDqhVg7oJQXwNshHjPfiAAWbCoDrFNZr1UH/6UGkcjhKS+1KfjcA71Df6nWGCXm0m8kFwqMsMfI+Mnqx5FnMQJNEIxmwwRhFwXQI+0p1wnaZqe12W0wmYW5SwK5qwIYcZBUwTb6hbBYaunlyjdnqdUPV1IlE3KBjbLnTc0rHimu9NfNu3n7J7IjByhXUhXiAvCB8iUk1VFYGJHttR2zTZshV8ANkQMs/E86FCg8x66oRFTNGhUUYwwlbUU8mlCfJIujs/d3qwmIUC70HbqkR6yoKf1f373Ud5o6ZA4GQQtm+49maTV7RpZw3D+AGlheLIWDDAd7lkdOP4E0JGQKJNUpzNPe1/aTZkpxAQPftDf7uIq3obWtOZ9pAszCFwcrNv4pOcvIfmZLITaOgz7rfgKjSxtiYJ19mCX1hJBUY2ERhK7I+F4vNE8qepXyaHGVda1Ll7t/eNTVuVEX0W9JVHlqUyFtibgdAUKw6jx2JNs2Ux7Yt4XjdufYB+7M0Zk+wY2/n7GyIbtwmfvcXBaHhH+/kNYCzK/o8aBT/za74RVdyAK/hDUoZtgqT1tdqDOyqMqepVev6YJAZRYiN9s57NFHgGI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
